### ISSUE TITLE
BUG - sr-latn language (code) is displaying Cyrillic in Django admin

### ISSUE THREAD

**Issue by roknicmilos** [vegaitsourcing/psihofon#103]

**Comment by roknicmilos** [comment]
For some reason, Django's `auth` app is using Cyrillic when `sr-latn` (Serbian Latin) is active.
Because the `User` model is moved to `psihofon` app, and the `Grup` model is not required for this project because it won't be used (at least for now), a workaround for the bug can be unregistering the `Group` model from Django Admin. 
This will remove the `auth` app entirely from the Django admin.
CC: @n-lekic

**Comment by n-lekic** [comment]
Problem with Django translations as well, not sure if we can override this, but I'll create an issue/PR later on for this on the django repo.
