### ISSUE TITLE
Fill JSON data files with the actual content

### ISSUE THREAD

**Issue by roknicmilos** [vegaitsourcing/psihofon#43]
In the frontend project (React Native application), there is the `assets/data/` directory with JSON files containing content examples. 
Populate those files with the actual content from [this document](https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=19wvqn3o45d8d#attid%253Datt_17c11a226ede354f_0.1_f_ktwmwtrx0).

**Comment by roknicmilos** [comment]
@n-lekic I'm gonna work on `assets/data/questionnaire.json`

**Comment by n-lekic** [comment]
@milos1302 taking `assets/data/organizations.json`

**Comment by roknicmilos** [comment]
@n-lekic I'm taking `selfEmpowermentExercise.json`

**Comment by n-lekic** [comment]
@milos1302 taking crisisExercises

**Comment by roknicmilos** [comment]
Taking the last one: `mentalStateExercises.json`

**Comment by roknicmilos** [comment]
There are 2 docs with content:
[doc 1](https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=19wvqn3o45d8d#attid%253Datt_17c11a226ede354f_0.1_f_ktwmwtrx0)
[doc 2](https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=19wvqn3o45d8d#attid%253Datt_17c119dcff150034_0.1_f_ktwmote20)
